services:

  postgres:
    image: postgres:17
    container_name: payment_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_password
      POSTGRES_DB: payment_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7
    container_name: payment_redis
    restart: unless-stopped
    ports:
      - "6380:6379"

volumes:
  postgres_data: